SELECT
    CT.TABLE_NAME,
    CT.COLUMN_NAME,
    C.CONSTRAINT_TYPE,
    C.CONSTRAINT_NAME
    
FROM
  (
      SELECT 
        CC.TABLE_NAME ,CONSTRAINT_TYPE, CC.COLUMN_NAME, CC.CONSTRAINT_NAME
      FROM 
        USER_CONSTRAINTS CT,
        USER_CONS_COLUMNS CC
      WHERE
      CT.TABLE_NAME = CC.TABLE_NAME 
      and CT.CONSTRAINT_NAME = CC.CONSTRAINT_NAME
      and CONSTRAINT_TYPE in ('P','U') 
      and GENERATED = 'USER NAME' ) C,
   USER_TAB_COLS CT
WHERE
    CT.TABLE_NAME = C.TABLE_NAME(+)
    AND CT.COLUMN_NAME = C.COLUMN_NAME(+)
    AND C.CONSTRAINT_TYPE in ('P','U')

ORDER BY TABLE_NAME;
    